import { foodCategories } from "./categories";
import { restaurantImages } from "./imagery";
import { Product } from "@/app/_types/product";

export const exploreCategories = ["Popular", ...foodCategories.map((category) => category.name), "Chicken", "Beef"];

export const exploreMenuItems: Product[] = [
  {
    id: "explore-naga-chicken",
    name: "Naga Chicken",
    slug: "naga-chicken",
    description: "Spicy grilled chicken with special sauce.",
    image: restaurantImages.nagaChicken,
    price: 280,
    oldPrice: 340,
    rating: 4.8,
    reviewCount: 410,
    categoryId: "Chicken",
    available: true,
  },
  {
    id: "explore-beef-tehari",
    name: "Beef Tehari",
    slug: "beef-tehari",
    description: "Traditional tehari with tender beef.",
    image: restaurantImages.tehari,
    price: 260,
    rating: 4.9,
    reviewCount: 850,
    categoryId: "Beef",
    available: true,
  },
  {
    id: "explore-chicken-chow-mein",
    name: "Chicken Chow Mein",
    slug: "chicken-chow-mein",
    description: "Stir-fried noodles with chicken & veggies.",
    image: restaurantImages.chowMein,
    price: 240,
    rating: 4.6,
    reviewCount: 320,
    categoryId: "Chinese",
    available: true,
  },
  {
    id: "explore-margherita-pizza",
    name: "Margherita Pizza",
    slug: "margherita-pizza",
    description: "Classic pizza with fresh mozzarella.",
    image: restaurantImages.pizza,
    price: 420,
    oldPrice: 500,
    rating: 4.7,
    reviewCount: 510,
    categoryId: "Pizza",
    available: true,
  },
  {
    id: "explore-bbq-chicken-wings",
    name: "BBQ Chicken Wings",
    slug: "bbq-chicken-wings",
    description: "Smoky & tangy chicken wings.",
    image: restaurantImages.wings,
    price: 300,
    oldPrice: 360,
    rating: 4.8,
    reviewCount: 290,
    categoryId: "Chicken",
    available: true,
  },
  {
    id: "explore-cold-coffee",
    name: "Cold Coffee",
    slug: "cold-coffee",
    description: "Chilled coffee with a creamy twist.",
    image: restaurantImages.coffee,
    price: 160,
    rating: 4.7,
    reviewCount: 380,
    categoryId: "Drinks",
    available: true,
  },
  {
    id: "explore-mango-juice", name: "Fresh Mango Juice", slug: "mango-juice",
    description: "Sweet mango, freshly blended and served chilled.",
    image: restaurantImages.mango, price: 140, rating: 4.8, reviewCount: 120,
    categoryId: "Drinks", available: true,
  },
  {
    id: "explore-brownie", name: "Chocolate Brownie", slug: "chocolate-brownie",
    description: "Warm chocolate brownie with vanilla ice cream.",
    image: restaurantImages.dessert, price: 220, rating: 4.9, reviewCount: 180,
    categoryId: "Desserts", available: true,
  },
  {
    id: "explore-seekh-kebab", name: "Seekh Kebab", slug: "seekh-kebab",
    description: "Smoky grilled kebabs with fresh onion and lime.",
    image: restaurantImages.kebab, price: 280, rating: 4.8, reviewCount: 150,
    categoryId: "Kebab", available: true,
  },
];
