// Restaurant-owned imagery; replace these paths when configuring another restaurant.
export const restaurantImages = {
  hero: "/images/hero.png",
  heroBanner: "/images/hero-rannaghor-banner.webp",
  familyFeastBanner: "/images/hero/family-feast-banner-v2.webp",
  weekendComboBanner: "/images/hero/weekend-combo-banner-v2.webp",
  biryani: "/images/generated/biryani.webp",
  burger: "/images/generated/burger.webp",
  pizza: "/images/generated/pizza.webp",
  chowMein: "/images/generated/chow-mein.webp",
  kebab: "/images/generated/kebab.webp",
  prawnRice: "/images/generated/prawn-rice.webp",
  mango: "/images/generated/mango.webp",
  dessert: "/images/generated/dessert.webp",
  grilledChicken: "/images/generated/grilled-chicken.webp",
  nagaChicken: "/images/generated/naga-chicken.webp",
  tehari: "/images/generated/tehari.webp",
  wings: "/images/generated/wings.webp",
  coffee: "/images/generated/coffee.webp",
  familyFeast: "/images/generated/family-feast.webp",
  lunch: "/images/generated/lunch.webp",
  weekend: "/images/generated/weekend.webp",
  interior: "/images/generated/interior.webp",
  interiorEvening: "/images/generated/interior-evening.webp",
  chef: "/images/generated/chef.webp",
  galleryBiryani: "/images/gallery/gallery-biryani-v2.webp",
  galleryInterior: "/images/gallery/gallery-interior-v2.webp",
  galleryKebab: "/images/gallery/gallery-kebab-v2.webp",
  galleryChef: "/images/gallery/gallery-chef-v2.webp",
  galleryDrinks: "/images/gallery/gallery-drinks-v2.webp",
  galleryDessert: "/images/gallery/gallery-dessert-v2.webp",
};
