import { restaurantImages } from "./imagery";
import { Product } from "@/app/_types/product";

export const popularProducts: Product[] = [
  {
    id: "prod-chicken-biryani",
    name: "Chicken Biryani",
    slug: "chicken-biryani",
    description: "Fragrant basmati rice with tender chicken, spices and love.",
    image: restaurantImages.biryani,
    price: 250,
    oldPrice: 320,
    rating: 4.8,
    reviewCount: 1200,
    categoryId: "cat-biryani",
    bestseller: true,
    available: true,
    variants: [
      { id: "single", name: "Single serving", price: 250 },
      { id: "large", name: "Large serving", price: 360 },
    ],
    addOns: [
      { id: "egg", name: "Boiled egg", price: 30 },
      { id: "borhani", name: "Borhani", price: 60 },
      { id: "salad", name: "Fresh salad", price: 40 },
    ],
  },
  {
    id: "prod-beef-burger",
    name: "Beef Burger",
    slug: "beef-burger",
    description: "Juicy beef patty with fresh veggies and special sauce.",
    image: restaurantImages.burger,
    price: 220,
    oldPrice: 280,
    rating: 4.7,
    reviewCount: 990,
    categoryId: "cat-burger",
    bestseller: true,
    available: true,
    variants: [
      { id: "regular", name: "Regular", price: 220 },
      { id: "double", name: "Double patty", price: 340 },
    ],
    addOns: [
      { id: "cheese", name: "Extra cheese", price: 40 },
      { id: "fries", name: "French fries", price: 100 },
      { id: "sauce", name: "House sauce", price: 25 },
    ],
  },
  {
    id: "prod-prawn-fried-rice",
    name: "Prawn Fried Rice",
    slug: "prawn-fried-rice",
    description: "Flavorful fried rice with fresh prawns and vegetables.",
    image: restaurantImages.prawnRice,
    price: 280,
    rating: 4.6,
    reviewCount: 640,
    categoryId: "cat-rice",
    bestseller: false,
    available: true,
  },
  {
    id: "prod-grilled-chicken-platter",
    name: "Grilled Chicken Platter",
    slug: "grilled-chicken-platter",
    description: "Perfectly grilled chicken with rice, salad and sauce.",
    image: restaurantImages.grilledChicken,
    price: 500,
    oldPrice: 650,
    rating: 4.7,
    reviewCount: 892,
    categoryId: "cat-kebab",
    bestseller: false,
    available: true,
  },
];
