import { restaurantImages } from "./imagery";
import { Product } from "@/app/_types/product";

export const popularProducts: Product[] = [
  {
    id: "prod-chicken-biryani",
    name: "Chicken Biryani",
    slug: "chicken-biryani",
    description: "Fragrant basmati rice with tender chicken, spices and love.",
    image: restaurantImages.biryani,
    price: 250,
    oldPrice: 320,
    rating: 4.8,
    reviewCount: 1200,
    categoryId: "cat-biryani",
    bestseller: true,
    available: true,
  },
  {
    id: "prod-beef-burger",
    name: "Beef Burger",
    slug: "beef-burger",
    description: "Juicy beef patty with fresh veggies and special sauce.",
    image: restaurantImages.burger,
    price: 220,
    oldPrice: 280,
    rating: 4.7,
    reviewCount: 990,
    categoryId: "cat-burger",
    bestseller: true,
    available: true,
  },
  {
    id: "prod-prawn-fried-rice",
    name: "Prawn Fried Rice",
    slug: "prawn-fried-rice",
    description: "Flavorful fried rice with fresh prawns and vegetables.",
    image: restaurantImages.prawnRice,
    price: 280,
    rating: 4.6,
    reviewCount: 640,
    categoryId: "cat-rice",
    bestseller: false,
    available: true,
  },
  {
    id: "prod-grilled-chicken-platter",
    name: "Grilled Chicken Platter",
    slug: "grilled-chicken-platter",
    description: "Perfectly grilled chicken with rice, salad and sauce.",
    image: restaurantImages.grilledChicken,
    price: 500,
    oldPrice: 650,
    rating: 4.7,
    reviewCount: 892,
    categoryId: "cat-kebab",
    bestseller: false,
    available: true,
  },
];
