import { restaurantImages } from "@/app/_data/imagery";
import type { OfferCampaign, OfferFilterOption } from "../_types/offer";

export const offerFilters: OfferFilterOption[] = [
  { id: "all", label: "All deals" },
  { id: "family", label: "Family" },
  { id: "combo", label: "Combos" },
  { id: "lunch", label: "Lunch" },
  { id: "weekend", label: "Weekend" },
];

export const offerCampaigns: OfferCampaign[] = [
  {
    id: "offer-family-feast",
    slug: "family-feast",
    title: "Family Feast",
    subtitle: "A generous spread made for sharing.",
    description: "Chicken biryani, roast, chilled drinks and a complimentary dessert for the whole table.",
    items: ["2 Chicken Biryani", "4 pcs Chicken Roast", "2 Drinks", "1 Dessert (Free)"],
    originalPrice: 1200,
    discountedPrice: 899,
    savingsBadge: "Save ৳301",
    image: restaurantImages.familyFeast,
    category: "family",
    availability: "Available every day",
    label: "Most popular",
    rating: 4.9,
    reviewCount: 380,
    featured: true,
  },
  {
    id: "offer-lunch-special",
    slug: "lunch-special",
    title: "Lunch Special",
    subtitle: "A satisfying midday meal for less.",
    description: "Fragrant chicken rice with salad and a refreshing drink, served as one quick combo.",
    items: ["Chicken Rice", "Fresh Salad", "Soft Drink"],
    originalPrice: 400,
    discountedPrice: 320,
    savingsBadge: "Save 20%",
    image: restaurantImages.lunch,
    category: "lunch",
    availability: "Sun–Thu, 12:00–4:00 PM",
    label: "Lunch only",
    rating: 4.8,
    reviewCount: 220,
  },
  {
    id: "offer-weekend-combo",
    slug: "weekend-combo",
    title: "Weekend Combo",
    subtitle: "More taste for relaxed weekends.",
    description: "A loaded burger, crispy chicken, fries and a cold drink for an easy weekend treat.",
    items: ["Beef Burger", "Crispy Chicken", "Fries", "Soft Drink"],
    originalPrice: 600,
    discountedPrice: 450,
    savingsBadge: "Save 25%",
    image: restaurantImages.weekend,
    category: "weekend",
    availability: "Friday and Saturday",
    label: "Weekend deal",
    rating: 4.9,
    reviewCount: 195,
  },
  {
    id: "offer-biryani-for-two",
    slug: "biryani-for-two",
    title: "Biryani for Two",
    subtitle: "Two plates, one delicious price.",
    description: "A pair of aromatic chicken biryanis with cooling borhani for an effortless meal together.",
    items: ["2 Chicken Biryani", "2 Borhani"],
    originalPrice: 790,
    discountedPrice: 649,
    savingsBadge: "Save ৳141",
    image: restaurantImages.biryani,
    category: "combo",
    availability: "Available every day",
    label: "Great for two",
    rating: 4.9,
    reviewCount: 310,
  },
  {
    id: "offer-grill-table",
    slug: "grill-table",
    title: "Grill Table",
    subtitle: "Smoky favourites for the whole table.",
    description: "Juicy grilled chicken, kebabs, aromatic rice and salad bundled for sharing.",
    items: ["Grilled Chicken", "6 pcs Kebab", "Family Rice", "Salad"],
    originalPrice: 1080,
    discountedPrice: 829,
    savingsBadge: "Save ৳251",
    image: restaurantImages.grilledChicken,
    category: "family",
    availability: "Available after 5:00 PM",
    label: "Dinner deal",
    rating: 4.8,
    reviewCount: 175,
  },
  {
    id: "offer-burger-buddy",
    slug: "burger-buddy",
    title: "Burger Buddy Deal",
    subtitle: "Double the burgers, double the fun.",
    description: "Two juicy beef burgers with a shared portion of fries and two chilled drinks.",
    items: ["2 Beef Burgers", "Large Fries", "2 Soft Drinks"],
    originalPrice: 720,
    discountedPrice: 549,
    savingsBadge: "Save ৳171",
    image: restaurantImages.burger,
    category: "combo",
    availability: "Available every day",
    label: "Buddy combo",
    rating: 4.8,
    reviewCount: 240,
  },
  {
    id: "offer-student-meal",
    slug: "student-meal",
    title: "Student Meal",
    subtitle: "A quick meal that fits the budget.",
    description: "Stir-fried chicken chow mein paired with a cold mango drink for busy afternoons.",
    items: ["Chicken Chow Mein", "Mango Drink"],
    originalPrice: 420,
    discountedPrice: 329,
    savingsBadge: "Save ৳91",
    image: restaurantImages.chowMein,
    category: "lunch",
    availability: "Sun–Thu, 12:00–5:00 PM",
    label: "Student favourite",
    rating: 4.7,
    reviewCount: 160,
  },
  {
    id: "offer-pizza-pairing",
    slug: "pizza-pairing",
    title: "Pizza Pairing",
    subtitle: "A complete comfort-food combo.",
    description: "Fresh margherita pizza, smoky wings and two cold drinks in one easy order.",
    items: ["Margherita Pizza", "6 pcs BBQ Wings", "2 Soft Drinks"],
    originalPrice: 910,
    discountedPrice: 699,
    savingsBadge: "Save ৳211",
    image: restaurantImages.pizza,
    category: "combo",
    availability: "Available every day",
    label: "Combo favourite",
    rating: 4.9,
    reviewCount: 285,
  },
];

export function getOfferSlug(offer: { id: string; slug?: string }): string {
  if (offer.slug) return offer.slug;
  return offer.id.replace(/^offer-/, "");
}

export function getOfferBySlug(slug: string): OfferCampaign | undefined {
  const cleanSlug = slug.trim().toLowerCase();
  return offerCampaigns.find(
    (offer) =>
      offer.slug === cleanSlug ||
      offer.id === cleanSlug ||
      offer.id === `offer-${cleanSlug}` ||
      offer.id.replace(/^offer-/, "") === cleanSlug,
  );
}
