import type { Product } from "@/app/_types/product";
import { popularProducts } from "@/app/_data/products";
import { exploreMenuItems } from "@/app/_data/explore-menu";
import { restaurantImages } from "@/app/_data/imagery";
import type { MenuCategoryFilter } from "../_types/menu";

export const menuCategories: MenuCategoryFilter[] = [
  { id: "all", label: "All" },
  { id: "biryani", label: "Biryani" },
  { id: "burger", label: "Burger" },
  { id: "pizza", label: "Pizza" },
  { id: "chinese", label: "Chinese" },
  { id: "kebab", label: "Kebab" },
  { id: "rice", label: "Rice" },
  { id: "drinks", label: "Drinks" },
  { id: "desserts", label: "Desserts" },
];

const additionalProducts: Product[] = [
  // ==================== BIRYANI ====================
  {
    id: "menu-shahi-kacchi",
    name: "Shahi Kacchi Biryani",
    slug: "shahi-kacchi-biryani",
    description: "Tender mutton, aromatic chinigura rice, potato, alubukhara and house-made borhani.",
    image: restaurantImages.galleryBiryani,
    price: 480,
    oldPrice: 520,
    rating: 4.9,
    reviewCount: 740,
    categoryId: "biryani",
    bestseller: true,
    available: true,
    variants: [
      { id: "regular", name: "Regular serving", price: 480 },
      { id: "large", name: "Large serving", price: 650 },
    ],
    addOns: [
      { id: "egg", name: "Boiled egg", price: 30 },
      { id: "borhani", name: "Borhani", price: 60 },
      { id: "firni", name: "Shahi firni", price: 90 },
    ],
  },
  {
    id: "menu-mutton-dum-biryani",
    name: "Hyderabadi Mutton Dum Biryani",
    slug: "hyderabadi-mutton-dum-biryani",
    description: "Slow-cooked spiced mutton layered with fragrant basmati rice, saffron and mint raita.",
    image: restaurantImages.biryani,
    price: 520,
    oldPrice: 580,
    rating: 4.8,
    reviewCount: 420,
    categoryId: "biryani",
    bestseller: false,
    available: true,
  },
  {
    id: "menu-beef-kala-tehari",
    name: "Old Dhaka Beef Kala Tehari",
    slug: "old-dhaka-beef-kala-tehari",
    description: "Traditional mustard oil tehari cooked with tender caramelized beef and green chillies.",
    image: restaurantImages.catBiryani,
    price: 290,
    rating: 4.9,
    reviewCount: 680,
    categoryId: "biryani",
    spicyLevel: 1,
    available: true,
  },
  {
    id: "menu-morog-polao",
    name: "Shahi Morog Polao",
    slug: "shahi-morog-polao",
    description: "Heritage Bengali Morog Polao with fragrant chinigura rice, chicken roast and golden beresta.",
    image: restaurantImages.ctaBiryani,
    price: 360,
    rating: 4.8,
    reviewCount: 310,
    categoryId: "biryani",
    available: true,
  },
  {
    id: "menu-kachhi-platter",
    name: "Grand Kacchi Biryani Platter",
    slug: "grand-kacchi-biryani-platter",
    description: "Generous mutton kacchi platter served with 2 chicken roasts, egg, borhani and salad.",
    image: restaurantImages.familyFeast,
    price: 780,
    oldPrice: 890,
    rating: 4.9,
    reviewCount: 520,
    categoryId: "biryani",
    bestseller: true,
    available: true,
  },

  // ==================== CHICKEN & CURRY (mapped to Rice / Kebab / Burger) ====================
  {
    id: "menu-butter-chicken",
    name: "Butter Chicken Masala",
    slug: "butter-chicken-masala",
    description: "Tender tandoori chicken simmered in rich creamy tomato and butter gravy with kasuri methi.",
    image: restaurantImages.popGrilledChicken,
    price: 340,
    rating: 4.8,
    reviewCount: 380,
    categoryId: "rice",
    available: true,
    addOns: [
      { id: "naan", name: "Butter Naan", price: 50 },
      { id: "cheese-naan", name: "Garlic Cheese Naan", price: 90 },
    ],
  },
  {
    id: "menu-garlic-roast-chicken",
    name: "Garlic Herb Roast Chicken",
    slug: "garlic-herb-roast-chicken",
    description: "Juicy oven-roasted half chicken infused with roasted garlic, fresh rosemary and herb jus.",
    image: restaurantImages.grilledChicken,
    price: 380,
    rating: 4.7,
    reviewCount: 240,
    categoryId: "kebab",
    available: true,
  },
  {
    id: "menu-crispy-fried-chicken",
    name: "Crispy Fried Chicken (4 pcs)",
    slug: "crispy-fried-chicken-4pcs",
    description: "Golden crunchy buttermilk fried chicken seasoned with special house spices and garlic dip.",
    image: restaurantImages.menuNagaChicken,
    price: 290,
    oldPrice: 350,
    rating: 4.7,
    reviewCount: 490,
    categoryId: "burger",
    available: true,
  },
  {
    id: "menu-chicken-tikka-masala",
    name: "Smoky Chicken Tikka Masala",
    slug: "smoky-chicken-tikka-masala",
    description: "Charcoal-grilled boneless chicken tikka tossed in a spicy, flavorful onion-tomato masala.",
    image: restaurantImages.wings,
    price: 320,
    rating: 4.8,
    reviewCount: 310,
    categoryId: "kebab",
    spicyLevel: 2,
    available: true,
  },

  // ==================== BEEF & GRILL (mapped to Rice / Kebab) ====================
  {
    id: "menu-beef-kala-bhuna",
    name: "Chittagong Beef Kala Bhuna",
    slug: "chittagong-beef-kala-bhuna",
    description: "Authentic dark caramelized beef cooked over slow heat with mustard oil, cloves and roasted spices.",
    image: restaurantImages.tehari,
    price: 380,
    oldPrice: 420,
    rating: 4.9,
    reviewCount: 890,
    categoryId: "rice",
    bestseller: true,
    spicyLevel: 2,
    available: true,
  },
  {
    id: "menu-beef-bhuna",
    name: "Old Dhaka Beef Bhuna",
    slug: "old-dhaka-beef-bhuna",
    description: "Slow-braised beef chunks in thick roasted onion gravy with ginger and whole spices.",
    image: restaurantImages.menuTehari,
    price: 320,
    rating: 4.8,
    reviewCount: 460,
    categoryId: "rice",
    available: true,
  },
  {
    id: "menu-beef-rezala",
    name: "Shahi Beef Rezala",
    slug: "shahi-beef-rezala",
    description: "Royal Mughlai style tender beef prepared in creamy yogurt, cashew paste and green chillies.",
    image: restaurantImages.catBiryani,
    price: 350,
    rating: 4.7,
    reviewCount: 290,
    categoryId: "rice",
    available: true,
  },
  {
    id: "menu-beef-chaap",
    name: "Beef Chaap Tawa Fry",
    slug: "beef-chaap-tawa-fry",
    description: "Marinated flattened beef steak shallow fried on tawa, served with luchi and cucumber salad.",
    image: restaurantImages.galleryKebab,
    price: 240,
    rating: 4.6,
    reviewCount: 340,
    categoryId: "kebab",
    available: true,
  },
  {
    id: "menu-sizzling-beef",
    name: "Sizzling Garlic Pepper Beef",
    slug: "sizzling-garlic-pepper-beef",
    description: "Tender sliced beef steak cooked with crushed black peppercorns and garlic on a hot iron skillet.",
    image: restaurantImages.kebab,
    price: 450,
    rating: 4.8,
    reviewCount: 210,
    categoryId: "kebab",
    available: true,
  },

  // ==================== CHINESE (5 additional + 1 explore = 6) ====================
  {
    id: "menu-szechuan-chicken",
    name: "Szechuan Chilli Chicken",
    slug: "szechuan-chilli-chicken",
    description: "Crispy chicken cubes tossed with dry red chillies, capsicum, garlic and spicy Szechuan sauce.",
    image: restaurantImages.catChinese,
    price: 290,
    rating: 4.7,
    reviewCount: 340,
    categoryId: "chinese",
    spicyLevel: 2,
    available: true,
  },
  {
    id: "menu-sweet-sour-prawns",
    name: "Sweet & Sour Crispy Prawns",
    slug: "sweet-sour-crispy-prawns",
    description: "Battered golden prawns glazed with sweet pineapple, bell peppers and tangy tomato reduction.",
    image: restaurantImages.prawnRice,
    price: 360,
    rating: 4.8,
    reviewCount: 280,
    categoryId: "chinese",
    available: true,
  },
  {
    id: "menu-chicken-manchurian",
    name: "Chicken Manchurian Gravy",
    slug: "chicken-manchurian-gravy",
    description: "Crispy chicken meatballs tossed in savory ginger, garlic, soy and spring onion gravy.",
    image: restaurantImages.menuChowMein,
    price: 280,
    rating: 4.6,
    reviewCount: 230,
    categoryId: "chinese",
    available: true,
  },
  {
    id: "menu-egg-fried-rice",
    name: "Wok Egg Fried Rice",
    slug: "wok-egg-fried-rice",
    description: "Aromatic wok-tossed jasmine rice with farm eggs, crunchy shredded carrots and scallions.",
    image: restaurantImages.catRice,
    price: 200,
    rating: 4.5,
    reviewCount: 310,
    categoryId: "chinese",
    available: true,
  },
  {
    id: "menu-vegetable-spring-rolls",
    name: "Crispy Vegetable Spring Rolls",
    slug: "crispy-vegetable-spring-rolls",
    description: "Four hand-rolled crispy golden pastries filled with julienned vegetables and sweet chilli dip.",
    image: restaurantImages.lunch,
    price: 180,
    rating: 4.6,
    reviewCount: 190,
    categoryId: "chinese",
    available: true,
  },

  // ==================== BURGER (5 additional + 1 popular = 6) ====================
  {
    id: "menu-bbq-bacon-burger",
    name: "Smoky BBQ Beef Bacon Burger",
    slug: "smoky-bbq-beef-bacon-burger",
    description: "Double smashed beef patties, smoked beef bacon, caramelized onions, cheddar and sweet BBQ.",
    image: restaurantImages.burger,
    price: 340,
    oldPrice: 390,
    rating: 4.9,
    reviewCount: 540,
    categoryId: "burger",
    bestseller: true,
    available: true,
  },
  {
    id: "menu-crispy-naga-burger",
    name: "Crispy Naga Chicken Burger",
    slug: "crispy-naga-chicken-burger",
    description: "Crunchy fried chicken breast dipped in spicy naga glaze, cooling coleslaw and melted cheese.",
    image: restaurantImages.catBurger,
    price: 260,
    rating: 4.8,
    reviewCount: 420,
    categoryId: "burger",
    spicyLevel: 3,
    available: true,
  },
  {
    id: "menu-double-cheese-burger",
    name: "Double Cheese Smashed Burger",
    slug: "double-cheese-smashed-burger",
    description: "Two prime smashed beef patties with double melted cheddar, secret burger sauce and pickles.",
    image: restaurantImages.popBurger,
    price: 310,
    rating: 4.8,
    reviewCount: 360,
    categoryId: "burger",
    available: true,
  },
  {
    id: "menu-mushroom-swiss-burger",
    name: "Mushroom Swiss Beef Burger",
    slug: "mushroom-swiss-beef-burger",
    description: "Flame-grilled beef patty smothered in sautéed garlic mushrooms and melted Swiss cheese.",
    image: restaurantImages.offerBurgerCombo,
    price: 290,
    rating: 4.7,
    reviewCount: 280,
    categoryId: "burger",
    available: true,
  },
  {
    id: "menu-grilled-teriyaki-burger",
    name: "Grilled Teriyaki Chicken Burger",
    slug: "grilled-teriyaki-chicken-burger",
    description: "Tender grilled chicken thigh glazed with Japanese teriyaki sauce and grilled pineapple slice.",
    image: restaurantImages.weekend,
    price: 270,
    rating: 4.6,
    reviewCount: 220,
    categoryId: "burger",
    available: true,
  },

  // ==================== PIZZA (5 additional + 1 explore = 6) ====================
  {
    id: "menu-chicken-cheese-pizza",
    name: "Chicken Cheese Pizza",
    slug: "chicken-cheese-pizza",
    description: "Roasted spiced chicken, mozzarella cheese, capsicum, red onions and Italian herb tomato sauce.",
    image: restaurantImages.pizza,
    price: 520,
    rating: 4.7,
    reviewCount: 360,
    categoryId: "pizza",
    available: true,
    variants: [
      { id: "medium-10", name: "10-inch Medium", price: 520 },
      { id: "large-12", name: "12-inch Large", price: 740 },
    ],
  },
  {
    id: "menu-pepperoni-beef-pizza",
    name: "Spicy Pepperoni & Beef Pizza",
    slug: "spicy-pepperoni-beef-pizza",
    description: "Generously loaded with beef pepperoni slices, seasoned minced beef, mozzarella and chilli flakes.",
    image: restaurantImages.catPizza,
    price: 580,
    oldPrice: 650,
    rating: 4.9,
    reviewCount: 480,
    categoryId: "pizza",
    bestseller: true,
    spicyLevel: 1,
    available: true,
  },
  {
    id: "menu-four-cheese-pizza",
    name: "Four Cheese Quattro Formaggi",
    slug: "four-cheese-quattro-formaggi",
    description: "Mozzarella, yellow cheddar, parmesan and creamy ricotta cheese on garlic herb brushed crust.",
    image: restaurantImages.menuPizza,
    price: 560,
    rating: 4.8,
    reviewCount: 290,
    categoryId: "pizza",
    available: true,
  },
  {
    id: "menu-bbq-chicken-pizza",
    name: "Smoky BBQ Chicken Pizza",
    slug: "smoky-bbq-chicken-pizza",
    description: "Tender BBQ glazed chicken, button mushrooms, red onions, mozzarella and smoky BBQ drizzle.",
    image: restaurantImages.pizza,
    price: 540,
    rating: 4.7,
    reviewCount: 310,
    categoryId: "pizza",
    available: true,
  },
  {
    id: "menu-naga-fire-pizza",
    name: "Naga Firecracker Pizza",
    slug: "naga-firecracker-pizza",
    description: "Fiery spiced shredded chicken, jalapeños, red paprika, mozzarella and spicy naga oil drizzle.",
    image: restaurantImages.catPizza,
    price: 530,
    rating: 4.8,
    reviewCount: 270,
    categoryId: "pizza",
    spicyLevel: 3,
    available: true,
  },

  // ==================== KEBAB (4 additional + 1 popular + 1 explore = 6) ====================
  {
    id: "menu-beef-seekh-kebab",
    name: "Beef Seekh Kebab",
    slug: "beef-seekh-kebab",
    description: "Charcoal-grilled minced beef skewers seasoned with aromatic spices, onion rings and mint chutney.",
    image: restaurantImages.galleryKebab,
    price: 340,
    rating: 4.8,
    reviewCount: 430,
    categoryId: "kebab",
    spicyLevel: 2,
    available: true,
  },
  {
    id: "menu-chicken-reshmi-kebab",
    name: "Silky Chicken Reshmi Kebab",
    slug: "silky-chicken-reshmi-kebab",
    description: "Melt-in-mouth boneless chicken cubes marinated in cashew paste, fresh cream and mild spices.",
    image: restaurantImages.catKebab,
    price: 320,
    rating: 4.9,
    reviewCount: 390,
    categoryId: "kebab",
    available: true,
  },
  {
    id: "menu-mutton-boti-kebab",
    name: "Tender Mutton Boti Kebab",
    slug: "tender-mutton-boti-kebab",
    description: "Succulent boneless mutton chunks marinated with green papaya, mustard oil and tandoori masala.",
    image: restaurantImages.kebab,
    price: 420,
    rating: 4.8,
    reviewCount: 310,
    categoryId: "kebab",
    available: true,
  },
  {
    id: "menu-hariyali-chicken-kebab",
    name: "Chicken Hariyali Kebab",
    slug: "chicken-hariyali-kebab",
    description: "Boneless chicken marinated with fresh coriander, mint leaves, green chillies and roasted cumin.",
    image: restaurantImages.popGrilledChicken,
    price: 300,
    rating: 4.7,
    reviewCount: 260,
    categoryId: "kebab",
    available: true,
  },

  // ==================== RICE (5 additional + 1 popular = 6) ====================
  {
    id: "menu-vegetable-fried-rice",
    name: "Vegetable Fried Rice",
    slug: "vegetable-fried-rice",
    description: "Wok-tossed rice with farm fresh egg, garden vegetables and aromatic spring onion.",
    image: restaurantImages.prawnRice,
    price: 210,
    rating: 4.5,
    reviewCount: 210,
    categoryId: "rice",
    available: true,
  },
  {
    id: "menu-garlic-butter-rice",
    name: "Garlic Butter Rice Platter",
    slug: "garlic-butter-rice-platter",
    description: "Fragrant basmati rice tossed in golden garlic butter, served with grilled chicken and salad.",
    image: restaurantImages.popPrawnRice,
    price: 320,
    rating: 4.8,
    reviewCount: 380,
    categoryId: "rice",
    available: true,
  },
  {
    id: "menu-beef-khichuri",
    name: "Bhuna Khichuri with Beef Kala Bhuna",
    slug: "bhuna-khichuri-beef-kala-bhuna",
    description: "Comforting moong dal khichuri cooked in ghee, served with tender beef kala bhuna and egg.",
    image: restaurantImages.catRice,
    price: 390,
    oldPrice: 440,
    rating: 4.9,
    reviewCount: 520,
    categoryId: "rice",
    bestseller: true,
    available: true,
  },
  {
    id: "menu-basmati-ghee-polao",
    name: "Shahi Basmati Ghee Polao",
    slug: "shahi-basmati-ghee-polao",
    description: "Traditional aromatic basmati rice cooked with pure ghee, whole cardamoms and fried cashews.",
    image: restaurantImages.lunch,
    price: 240,
    rating: 4.7,
    reviewCount: 290,
    categoryId: "rice",
    available: true,
  },
  {
    id: "menu-special-mixed-rice",
    name: "Special Mixed Meat Fried Rice",
    slug: "special-mixed-meat-fried-rice",
    description: "Wok-fried rice loaded with tiger prawns, chicken cubes, beef strips, egg and scallions.",
    image: restaurantImages.prawnRice,
    price: 340,
    rating: 4.8,
    reviewCount: 410,
    categoryId: "rice",
    available: true,
  },

  // ==================== DRINKS (4 additional + 2 explore = 6) ====================
  {
    id: "menu-mango-lassi",
    name: "Thick Mango Lassi",
    slug: "thick-mango-lassi",
    description: "Creamy whole milk yogurt blended with sweet ripe Rajshahi mangoes and a touch of cardamom.",
    image: restaurantImages.mango,
    price: 180,
    rating: 4.8,
    reviewCount: 265,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "menu-shahi-borhani",
    name: "Classic Shahi Borhani",
    slug: "classic-shahi-borhani",
    description: "Traditional spiced yogurt digestive drink with fresh mint, coriander, roasted cumin and black salt.",
    image: restaurantImages.galleryDrinks,
    price: 90,
    rating: 4.9,
    reviewCount: 620,
    categoryId: "drinks",
    bestseller: true,
    available: true,
  },
  {
    id: "menu-mint-lemonade",
    name: "Sparkling Mint Lemonade",
    slug: "sparkling-mint-lemonade",
    description: "Crushed fresh mint leaves, zesty lemon juice and sparkling soda with pink Himalayan rock salt.",
    image: restaurantImages.catDrinks,
    price: 130,
    rating: 4.7,
    reviewCount: 210,
    categoryId: "drinks",
    available: true,
  },
  {
    id: "menu-strawberry-shake",
    name: "Fresh Strawberry Milkshake",
    slug: "fresh-strawberry-milkshake",
    description: "Creamy milkshake prepared with real strawberries, fresh dairy milk and vanilla bean ice cream.",
    image: restaurantImages.menuColdCoffee,
    price: 200,
    rating: 4.8,
    reviewCount: 180,
    categoryId: "drinks",
    available: true,
  },

  // ==================== DESSERTS (5 additional + 1 explore = 6) ====================
  {
    id: "menu-chocolate-lava-cake",
    name: "Chocolate Lava Cake",
    slug: "chocolate-lava-cake",
    description: "Warm Belgian chocolate cake with a rich molten chocolate centre, served warm.",
    image: restaurantImages.galleryDessert,
    price: 240,
    rating: 4.9,
    reviewCount: 395,
    categoryId: "desserts",
    bestseller: true,
    available: true,
  },
  {
    id: "menu-shahi-firni",
    name: "Shahi Matka Firni",
    slug: "shahi-matka-firni",
    description: "Slow-cooked aromatic ground rice pudding infused with saffron, rosewater and toasted pistachios.",
    image: restaurantImages.dessert,
    price: 120,
    rating: 4.9,
    reviewCount: 470,
    categoryId: "desserts",
    available: true,
  },
  {
    id: "menu-gulab-jamun",
    name: "Gulab Jamun with Rabri (2 pcs)",
    slug: "gulab-jamun-with-rabri",
    description: "Golden fried khoya milk dumplings soaked in cardamom syrup, topped with thick condensed rabri.",
    image: restaurantImages.catDessert,
    price: 160,
    rating: 4.8,
    reviewCount: 320,
    categoryId: "desserts",
    available: true,
  },
  {
    id: "menu-rasmalai",
    name: "Delicate Kesar Rasmalai (2 pcs)",
    slug: "delicate-kesar-rasmalai",
    description: "Soft spongy cottage cheese patties soaked in saffron-flavored thickened cardamom milk.",
    image: restaurantImages.galleryDessert,
    price: 180,
    rating: 4.9,
    reviewCount: 290,
    categoryId: "desserts",
    available: true,
  },
  {
    id: "menu-kesar-kulfi",
    name: "Traditional Matka Kulfi",
    slug: "traditional-matka-kulfi",
    description: "Authentic slow-reduced clotted cream kulfi flavored with saffron, cardamom and almond flakes.",
    image: restaurantImages.dessert,
    price: 140,
    rating: 4.8,
    reviewCount: 210,
    categoryId: "desserts",
    available: true,
  },
];

export const menuProducts: Product[] = [
  ...popularProducts,
  ...exploreMenuItems,
  ...additionalProducts,
];

export function normalizeCategory(categoryId: string) {
  return categoryId.toLowerCase().replace(/^cat-/, "");
}
